### ISSUE TITLE
Problema na interface da página

### ISSUE THREAD

**Issue by Alyssonmach** [algebralinearufcg/algebralinearufcg.github.io#2]
Boa tarde aos envolvidos no projeto.

Venho comunicar que foi encontrado um bug em seu site. Na visualização em celular, não está tão intuitivo a visualização dos programas, pois não há nada indicando que se deve rolar para direita ou esquerda na hora de visualizar os mesmos.

- Segue abaixo a imagem:
<img width="375" alt="imagemtela" src="https://user-images.githubusercontent.com/58775072/80244244-ff725a00-863e-11ea-90c4-83d7de774822.png">

Espero que vocês corrijam esse problema.

Saudações, usuário.

**Comment by algebralinearufcg** [comment]
Oi Alysson.

Muito obrigado pelo feedback! O problema já está resolvido!
![caricato](https://user-images.githubusercontent.com/62623572/80252812-706d3e00-864e-11ea-9c37-6ce22f712265.png)
